// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PsychoTriage.Infrastructure.Persistence;

#nullable disable

namespace PsychoTriage.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324211420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PsychoTriage.Domain.Entities.TriageEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicalProfile")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FunctionalImpairment")
                        .HasColumnType("boolean");

                    b.Property<int>("Gad7Score")
                        .HasColumnType("integer");

                    b.Property<int>("Phq9Score")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SelfHarmHistory")
                        .HasColumnType("boolean");

                    b.Property<int>("SocialSupportLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("SubstanceUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("SuicidalIdeation")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TriageEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
